version: '3.3'

services:
  hello-world:
    container_name: react-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true